import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Suspense } from "react";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Suspense>
      <html lang="en">
        <head>
          <script
            {...{ src: "https://unpkg.com/prettier@3.5.3/standalone.js" }}
          />

          {[
            "acorn",
            "angular",
            "babel",
            "flow",
            "glimmer",
            "graphql",
            "html",
            "markdown",
            "meriyah",
            "postcss",
            "typescript",
            "yaml",
          ].map((plugin) => (
            <script
              key={plugin}
              {...{
                src: `https://unpkg.com/prettier@3.5.3/plugins/${plugin}.js`,
              }}
            />
          ))}
        </head>

        <body className={inter.className}>{children}</body>
      </html>
    </Suspense>
  );
}
