import { Metadata } from "next";
import { Suspense } from "react";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: Readonly<RootLayoutProps>) => (
  <Suspense>
    <html {...{ lang: "ko" }}>
      <head>
        <script
          {...{ src: "https://unpkg.com/prettier@3.5.3/standalone.js" }}
        />

        {[
          "acorn",
          "angular",
          "babel",
          "flow",
          "glimmer",
          "graphql",
          "html",
          "markdown",
          "meriyah",
          "postcss",
          "typescript",
          "yaml",
        ].map((plugin) => (
          <script
            key={plugin}
            {...{
              src: `https://unpkg.com/prettier@3.5.3/plugins/${plugin}.js`,
            }}
          />
        ))}
      </head>

      <body {...{ children }} />
    </html>
  </Suspense>
);

interface RootLayoutProps {
  children: React.ReactNode;
}

export default RootLayout;
